service: developers-application-backend
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

functions:
  developers:
    handler: handler.app
    events:
        - http:
            method: get
            path: developers
            cors: true

        - http:
            method: put
            path: developers/{id}
            cors: true

        - http:
            method: post
            path: developers
            cors: true

        - http:
            method: delete
            path: developers/{id}
            cors: true


#GET
# idofwogrk.aws.amazon.com/developers

#PUT
# sahuiefwewe.aws.amazon.com/developers/3 <----- Path paramenter + request body

#POST
# awdefegerg.aws.amazon.com/developers <---- + Request body

# DELETE
# efeiugheir.aws.amazon.com/developers/2 <------- + Path Parameter
